PRAGMA_SETTING         = "PRAGMA FOREIGN_KEYS = ON;"

GET_ALL_PLAYER         = "SELECT * FROM PLAYER;"

GET_ALL_USER           = "SELECT * FROM USER;"

GET_ALL_RATING         = "SELECT * FROM DETAIL_INFO;"

GET_USER_BY_UID        = "SELECT * FROM USER WHERE UID = ?;"

INSERT_USER            = "INSERT INTO USER(UID) VALUES (?)"

GET_ALL_DETAIL_INFO    = "SELECT * FROM DETAIL_INFO;"

GET_PLAYER_BY_GID      = "SELECT * FROM PLAYER WHERE GID = ?;"

GET_PLAYER_BY_PID      = "SELECT * FROM PLAYER WHERE PID = ?;"

GET_DETAIL_INFO_BY_GID = "SELECT * FROM DETAIL_INFO WHERE GID = ?;"

INSERT_PLAYER          = "INSERT INTO PLAYER (PID, GID, BINFO) VALUES (?, ?, ?);"

UPDATE_PLAYER_BINFO    = "UPDATE PLAYER SET BINFO = ? WHERE GID = ?;"

DELETE_PLAYER_BY_GID   = "DELETE FROM PLAYER WHERE GID = ?;"

RATE_PLAYER            = "INSERT INTO DETAIL_INFO (GID, UID, MSG, TIME) VALUES (?, ?, ?, ?);"

LIST_RATING            = "SELECT P.GID, P.BINFO, COUNT(*) AS COUNT, MAX(D.TIME) AS MAX_TIME " \
                         "FROM PLAYER AS P LEFT JOIN DETAIL_INFO AS D USING (GID) " \
                         "GROUP BY P.GID"

COUNT_PLAYER           = "SELECT COUNT(*) FROM PLAYER;"